services:
  nest-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-backend
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/nestdb
    entrypoint: ['/bin/sh', '-lc']
    command: '/app/entrypoint.sh'
    depends_on:
      - mongo
      - ngrok
    env_file:
      - .env.local

  ngrok:
    image: ngrok/ngrok:alpine
    command:
      - http
      - --region=eu
      - nest-backend:8080
    ports:
      - '4040:4040'
    env_file:
      - .env.local

  mongo:
    image: mongo:6
    command: ['--quiet', '--logpath', '/data/db/mongo.log', '--logappend']
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
